---

blank_issues_enabled: false
contact_links:
  - name: Questions / Support
    url: https://github.com/baldusi/BalduHandbrake/discussions
    about: Please ask general questions, usage help, or open-ended discussions in the Discussions tab.